import React from 'react'

export default function More() {
  return (
    <div class="container" style={{maxWidth: "50%"}}>
        <h1 class="display-6">Early History</h1>
<p>Founded as Big Tree Entertainment, but popularly known as BookMyShow, the company was founded by Ashish Hemrajani, Parikshit Dar and Rajesh Balpande, all three alumni of Sydenham Institute of Management, Mumbai University. They had been working for J.W. Thompson, SPAR and Chatterjee Soros Group respectively, before they hung up their corporate boots to start BookMyShow officially in 2007. The major purpose of this start-up was to bring the concept of online movie ticketing to India.</p>
<h2 class="display-6">Services</h2>
<p>Apart from being an online ticketing portal, BookMyShow also offers information about upcoming movies and events, show timings, venue details and artist bios. Started about a year and a half ago, BookMyShow’s user generated movie reviews and ratings started as an engagement exercise aimed at hastening the decision-making process but later grew in popularity. Today, it ranks amongst one of the most reliable sources of information related to movies. With the focus on content and advertising gaining supreme importance, this move has helped BookMyShow differentiate from its other competitors. With growth as the target. BookMyShow's partnering with cinemas like Cinepolis, PVR Cinemas, and companies like Snapdeal has only just added extra shining stars to it's profile. Non-Movie partnering with sporting events also helps them in the same.</p>
<h2 class="display-6">Funding & Company Valuation</h2>
<p>Soon after BookMyShow was launched, the company was invested in by Network18 which marked the company's first round of funding in 2007. In August 2012, Accel Partners invested USD 18 million in BookMyShow. After this investment the company valuation stood at USD 58.33 million. In June 2014, BookMyShow announced that it has raised USD 25 million from SAIF Partners, another global equity investor. The recent investment marks a quantum leap to a valuation of USD166.67 million from USD 58.33 million, previously raised in 2012. In July 2016, Bigtree Entertainment, which owns and operates BookMyShow raised 5.5 billion ($81.5 million) led by the US-based private equity firm Stripes Group valuing the company at more than Rs. 3,000 Crores. The Company intends to use this growth capital to enhance its convenience and offerings to customers as it evolves from a ticketing portal to a true ‘entertainment destination’ as well as entering new international territories, such as Indonesia and Sri Lanka.</p>
<h2 class="display-6">Acquisitions</h2>
<p>In March 2013, BookMyShow acquired TicketGreen, a Chennai-based online ticketing company. In February 2015, the company bought a majority stake in Eventifier for $2 million for an all cash deal, with existing investors exiting the company. Started in June 2012 by Jazeel Badur Ferry, Nasim Zeeshan and Mohammed Saud, Eventifier allows event organizers to archive event related content like photos, videos, slides, tweets and conversations from the web to a dedicated events page. In March 2016, BookMyShow acquired Fantain Sports, a Chennai-based fan management and analytics startup, for an undisclosed amount, to expand its reach and grow its user base. Fantain offers fan engagement through mobile and web solutions, stubs and widgets which can be used in channels to capture and send fan interaction via TV, digital, web, POS etc. to its database for analysis.</p>
    </div>
  )
}
